[build]
  command = "npm run build && cp netlify/redirects.production dist/_redirects"
  publish = "dist"

[context.production]
  command = "npm run build && cp netlify/redirects.production dist/_redirects"

[context.staging]
  command = "npm run build && cp netlify/redirects.staging dist/_redirects"
